version: '3.8'  
  
services:  
  frontend:  
    build:  
      context: .  
      dockerfile: Dockerfile
      args:
        REACT_APP_MODE: prod
    ports:  
      - "3080:80"  
    depends_on:  
      - backend
  
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "8080:8000"