/**
 * Terms and Conditions Translations
 */

export const en = {
    title: "Terms of Use for DFO Pacific AI Hub",
    compliance: {
      title: "Compliance with Guidelines",
      text: "All users must adhere to the Treasury Board Secretariat's (TBS) Guidelines on the use of Generative AI within the Public Service."
    },
    prohibition: {
      title: "Prohibition on Sensitive Information",
      text: "Users are strictly prohibited from using any sensitive or protected information when interacting with the application."
    },
    intendedUse: {
      title: "Intended Use",
      text: "The application is designed to be a productivity tool and should not be used as a replacement for human intelligence and judgment. Users are responsible for verifying the accuracy of the outputs generated by the app."
    },
    experimental: {
      title: "Experimental Release",
      text: "The application is currently in an experimental release phase under development. As such, there are no guarantees regarding its performance or reliability during this trial period."
    },
    ethics: {
      title: "Values and Ethics",
      text: "Usage of the application is subject to the Values and Ethics Code for the Public Sector. Users must ensure that their interactions with the app align with the ethical standards and values expected of public sector employees."
    },
    revocation: {
      title: "Revocation of Access",
      text: "Failure to comply with the above terms may result in the revocation of access to the application."
    },
    // Modal specific translations
    modal: {
      title: "Terms and Conditions",
      acceptButton: "Accept",
      declineButton: "Decline",
      closeButton: "Close"
    }
  };
  
  export const fr = {
    title: "Conditions d'utilisation du hub IA du MPO",
    compliance: {
      title: "Conformité aux directives",
      text: "Tous les utilisateurs doivent se conformer aux directives du Secrétariat du Conseil du Trésor (SCT) sur l'utilisation de l'IA générative dans la fonction publique."
    },
    prohibition: {
      title: "Interdiction des informations sensibles",
      text: "Les utilisateurs sont strictement interdits d'utiliser des informations sensibles ou protégées lors de l'interaction avec l'application."
    },
    intendedUse: {
      title: "Utilisation prévue",
      text: "L'application est conçu pour être un outil de productivité et ne doit pas être utilisé comme un substitut à l'intelligence et au jugement humains. Les utilisateurs sont responsables de vérifier l'exactitude des résultats générés par l'application."
    },
    experimental: {
      title: "Version expérimentale",
      text: "L'application est actuellement en phase de version expérimentale en cours de développement. En tant que tel, il n'y a aucune garantie quant à ses performances ou sa fiabilité pendant cette période d'essai."
    },
    ethics: {
      title: "Valeurs et éthique",
      text: "L'utilisation de l'application est soumise au Code de valeurs et d'éthique du secteur public. Les utilisateurs doivent s'assurer que leurs interactions avec l'application sont conformes aux normes éthiques et aux valeurs attendues des employés du secteur public."
    },
    revocation: {
      title: "Révocation de l'accès",
      text: "Le non-respect des conditions ci-dessus peut entraîner la révocation de l'accès à l'application."
    },
    // Modal specific translations
    modal: {
      title: "Conditions générales d'utilisation",
      acceptButton: "Accepter",
      declineButton: "Refuser",
      closeButton: "Fermer"
    }
  };
  
  /**
   * Get terms translations for the specified language
   * 
   * @param {string} language - Language code ('en' or 'fr')
   * @returns {Object} - Translations object
   */
  export function getTermsTranslations(language) {
    return language === 'fr' ? fr : en;
  }